set_property PACKAGE_PIN K17 [get_ports {in_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_clk}]

set_property PACKAGE_PIN D18 [get_ports {y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y[0]}]
set_property PACKAGE_PIN G14 [get_ports {y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y[1]}]
set_property PACKAGE_PIN M15 [get_ports {y[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y[2]}]
set_property PACKAGE_PIN M14 [get_ports {y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y[3]}]

set_property PACKAGE_PIN V12 [get_ports {out_chip_select}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_chip_select}]
set_property PACKAGE_PIN J15 [get_ports {in_miso}]
set_property IOSTANDARD LVCMOS33 [get_ports {in_miso}]
set_property PACKAGE_PIN H15 [get_ports {out_sclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_sclk}]

set_property PACKAGE_PIN Y16 [get_ports {enable}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable}]


set_property PACKAGE_PIN D19 [get_ports {TMDS[0]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDS[0]}]
set_property PACKAGE_PIN D20 [get_ports {TMDSB[0]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDSB[0]}]
set_property PACKAGE_PIN C20 [get_ports {TMDS[1]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDS[1]}]
set_property PACKAGE_PIN B20 [get_ports {TMDSB[1]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDSB[1]}]
set_property PACKAGE_PIN B19 [get_ports {TMDS[2]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDS[2]}]
set_property PACKAGE_PIN A20 [get_ports {TMDSB[2]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDSB[2]}]
set_property PACKAGE_PIN H16 [get_ports {TMDS[3]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDS[3]}]
set_property PACKAGE_PIN H17 [get_ports {TMDSB[3]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDSB[3]}]
set_property PACKAGE_PIN K17 [get_ports {sys_clk}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sys_clk}]
set_property PACKAGE_PIN K18 [get_ports {reset_btn}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reset_btn}]
